### PR TITLE
Added explanations from @viktorklang related to the content of the 'protocols' folder

### PR DESCRIPTION
**Pull request by ChristopherAndre**
Following a discussion on gitter, I am adding the answer from @viktorklang to the documentation for future reference.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ChristopherAndre,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @ChristopherAndre,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by ChristopherAndre** [comment]
CLA accepted!

**Comment by viktorklang** [comment]
Thank you, @ChristopherAndre! :+1:

**Pull request merged**
