### PR TITLE
Upgrade to akka-persistence-spanner 1.0.0-RC5

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

**Comment by hseeberger** [comment]
Travis CI failed, but as far as I can see, not related to this change. I have restarted the build ... let's see.

**Comment by hseeberger** [comment]
@jroper any ideas why this is failing CI?

**Comment by hseeberger** [comment]
@marcellanz or @sleipnir, would you please approve this PR now that the CI tests are green?

**Comment by marcellanz** [comment]
@hseeberger we are not part of the core team, hence have no permission to do so. Either James or Peter might be able to do that or Viktor.

**Comment by hseeberger** [comment]
OK, as nobody of the core team wants to review, I am going to use my superpowers and get this PR merged.

**Comment by marcellanz** [comment]
mgc

**Comment by marcellanz** [comment]
^^ (I'm sorry for my emotional outbreak, of adding a GIF)

**Comment by hseeberger** [comment]
😂

**Pull request merged**
