### PR TITLE
Split reflect-config's by jar (in HOCON)

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by viktorklang** [comment]
@dwijnand I don't think suffixing the names of the files `.json.conf` will be good given this native-build instruction in the `build.sbt`: `"-H:IncludeResources=.+\\.conf",`

**Comment by viktorklang** [comment]
@dwijnand I suspect that we might be adding a bit too much information to the reflection with our new AutomaticFeatures:

```
[info] [cloudstate-proxy-core:46874]     analysis: 991,913.29 ms,  6.40 GB
[error] Fatal error: java.lang.OutOfMemoryError
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[error] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[error] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[error] 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
[error] 	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[error] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:357)
[error] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:501)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.executeCompilation(NativeImageBuildServer.java:406)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$processCommand$8(NativeImageBuildServer.java:343)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.withJVMContext(NativeImageBuildServer.java:424)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.processCommand(NativeImageBuildServer.java:340)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.processRequest(NativeImageBuildServer.java:284)
[error] 	at com.oracle.svm.hosted.server.NativeImageBuildServer.lambda$serve$7(NativeImageBuildServer.java:244)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.OutOfMemoryError: Java heap space
[error] Error: Image build request failed with exit status 1
[error] com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
[error] 	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1527)
[error] 	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1289)
[error] 	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1250)
[error] 	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1209)
[error] 	at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1707)
[error] stack trace is suppressed; run last proxy-core / Graalvm-native-image / packageBin for the full output
```

**Comment by dwijnand** [comment]
From my changes only a few extra things are being added, things like "NullSerializer".  Where are you seeing that error?

**Comment by dwijnand** [comment]
> @dwijnand I don't think suffixing the names of the files `.json.conf` will be good given this native-build instruction in the `build.sbt`: `"-H:IncludeResources=.+\\.conf",`

Yeah, that might prove to be a problem.  I'll keep an eye on it.

**Comment by viktorklang** [comment]
@dwijnand I got that when trying to run the nativePackager

**Pull request merged**
