### PR TITLE
Get GraalVM container images from GitHub packages

### PR DESCRIPTION
**Pull request by raboof**
Since they have disappeared from Docker Hub:
https://www.graalvm.org/docs/getting-started/#graalvm-community-container-images

May need an update to CircleCI to set up credentials to log in to
GitHub, let's see.

### CODE REVIEW

**Comment by pvlugter** [comment]
I've updated the GITHUB_TOKEN env var to the token currently used for cloudstatebot, and reverted back the latest commits. But realising that the secrets will of course not be available to pull requests from forks. If we need to authenticate with secrets, then we'll likely need a different approach here, as we shouldn't enable secrets for forked pull requests.

**Comment by pvlugter** [comment]
Ok, looking at this more closely. So the older version of Graal that we use is published to `docker.pkg.github.com/graalvm/container/community` but `docker.pkg.github.com` requires authentication for all pulls. The newer Graal docker images are at `ghcr.io/graalvm/graalvm-ce`, which allows unauthenticated pulls, but doesn't have the older version that we're using. Trying an upgrade to `20.3.1` and it doesn't build — will need changes. So possibilities as I see it:

- create some public guest credentials that can go into CI build directly
- republish the docker image for the older version to another repository
- update to a newer Graal version so we can pull from ghrc.io instead (this is what we'll want to do at some point anyway)

**Comment by pvlugter** [comment]
I'm trying a minimal Graal update in #519

**Comment by pvlugter** [comment]
Closing this one, with #519 passing tests.

**Comment by raboof** [comment]
Great, thx!

**Pull request closed without merging**
