### PR TITLE
Add DI-friendly entity factory to java support

### PR DESCRIPTION
**Pull request by pvlugter**
Simplied version of #227 for #219 as discussed in https://github.com/cloudstateio/cloudstate/pull/227#pullrequestreview-402349893.

### CODE REVIEW

**Comment by sleipnir** [comment]
It would be interesting to have a branch of this PR

**Comment by sleipnir** [comment]
@pvlugter After adjusts in cloudstate-springboot-starter to use new cloudstate-java-support entity constructor the build passed 100%

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for spring-boot-cloudstate-starter 0.4.3:
[INFO] 
[INFO] spring-boot-cloudstate-starter ..................... SUCCESS [  0.179 s]
[INFO] cloudstate-springboot-starter ...................... SUCCESS [  8.036 s]
[INFO] examples ........................................... SUCCESS [  0.009 s]
[INFO] cloudstate-springboot-example ...................... SUCCESS [ 18.815 s]
[INFO] cloudstate-springboot-jsr330 ....................... SUCCESS [  8.705 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.035 s
[INFO] Finished at: 2020-04-29T23:32:10-03:00
[INFO] ------------------------------------------------------------------------

``` 
For me it's OK and we can merge if everyone agrees

**Comment by sleipnir** [comment]
Client side code in https://github.com/sleipnir/spring-boot-cloudstate-starter/tree/wip-di-support

**Comment by pvlugter** [comment]
@sleipnir, great, sounds good. Let's close the other PR and use this one then.

**Comment by sleipnir** [comment]
Hi @pvlugter any progress here?

**Comment by pvlugter** [comment]
Just waiting on review. @jroper, can you take a look?

**Comment by viktorklang** [comment]
Pinging @jroper so we can get this through the pipeline

**Comment by sleipnir** [comment]
@pvlugter  Sorry to ask again but is there any chance that this will progress?

**Comment by pvlugter** [comment]
@sleipnir sure, sorry for the delay. I'll merge based on your review, and will publish a new version of java-support.

**Comment by pvlugter** [comment]
@sleipnir, cloudstate-java-support 0.5.1 has these changes, and is published and synced to maven central

**Comment by sleipnir** [comment]
Awesome @pvlugter thanks!

**Comment by sleipnir** [comment]
Hi @pvlugter / @viktorklang 
I chage springboot-support to version 0.5.1 and everything worked as expected.
I think we could evaluate the official entry of springboot support on Cloudstate.

**Comment by viktorklang** [comment]
@sleipnir Cool that it works as advertised! :)

**Comment by kwehden** [comment]
This is excellent! @sleipnir, a great piece of work.  I think we should promote springboot support to official!

**Comment by sleipnir** [comment]
Thanks @kwehden good to know that it is a desired support. Thanks @viktorklang

**Comment by ralphlaude** [comment]
@sleipnir well done! :)

**Comment by pvlugter** [comment]
:+1: Promoting to official support sounds good (#330).

**Pull request merged**
