### PR TITLE
Update README.md to further enhance its flow and readability.

### LINKED ISSUE #86: Make a handful of (minor) updates to README.md to enhance its flow and readability.
- The CloudState `README.md` is just about the coolest guide that I've seen in a great long while; and I've pretty much seen them all. 
- The coherent narrative laid out in the `README.md` has done nothing less for me than give me a manifesto for building (and using) next generation serverless, the way it _should_ be done. Kudos 👍 
- It has, in short order, nicely framed `FaaS` in the context it should be seen; a first (important) step toward stateful cloud computing, but a first step nonetheless 🌩 
- With that, and with utmost respect for the design captured by the author(s) of this terrific `README.md`, I suggest that we make a handful of (minor) updates to it so as to enhance its flow and readability even more than it currently stands.

### PR DESCRIPTION
**Pull request by akramtexas**
Fix #86 

- These are tweaks to the fabulous CloudState `README.md` to further enhance the flow and readability of its narrative. This PR supplants PR #87

### CODE REVIEW

**Comment by akramtexas** [comment]
@viktorklang - Requesting you to please add yourself as a reviewer of this PR (as I currently don't have permissions to do so), thanks.

**Comment by viktorklang** [comment]
Great stuff, thanks @akramtexas!

**Comment by akramtexas** [comment]
> Great stuff, thanks @akramtexas!

Thanks a ton, @viktorklang 🆒 Working alongside wildly skilled developers is always cool, but when they also happen to be awesome individuals, it's plain awesome!

**Comment by viktorklang** [comment]
@akramtexas ^^

**Pull request merged**
