### PR TITLE
Fix links in README

### PR DESCRIPTION
**Pull request by ticofab**
Simply fixes a couple broken links in the Readme.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @ticofab,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by viktorklang** [comment]
Apologies for the delay here, @ticofab—there's been some package renames since this was opened. Care to update and refresh the PR?

**Comment by viktorklang** [comment]
Thanks @ticofab!

**Comment by ticofab** [comment]
Oh wait there wasn't any change yet - I was just syncing my own branch with the original :)

**Comment by viktorklang** [comment]
@ticofab Oh, then rebase and let me know when things are ready to merge :)

**Comment by ticofab** [comment]
hey @viktorklang I re-fixed most offending links 😄 there is one tho that I wasn't sure how to fix, which is 
```
[`entity.js`](node-support/src/entity.js)
```
, so maybe you or @jroper can fix that one before merging? :)

**Comment by viktorklang** [comment]
Thanks @ticofab, the documentation will get better with each such PR :)

**Pull request merged**
