### PR TITLE
Use constants in EventSourcedJournal too

### PR DESCRIPTION
**Pull request by janory**
Analogous to the EventSourcedService, use OperatorConstants instead of hardcoded values

### CODE REVIEW

**Comment by viktorklang** [comment]
Thanks @janory! :)

**Comment by viktorklang** [comment]
@janory Seems like this PR has conflics which needs to be resolved before I can merge, let me know when it's ready for merging, thanks! :)

**Comment by janory** [comment]
@viktorklang updated!

**Comment by viktorklang** [comment]
@jroper There's been some changes in the files referred to by this PR, would you mind having a look as to what makes sense for current master?

**Pull request merged**
