### PR TITLE
Allow TCK to run as docker container

### PR DESCRIPTION
**Pull request by pvlugter**
For #216. Some minimal changes on the TCK so that it can be run independently, using docker, to be part of language support builds.

The parts of the TCK tests that manage processes have been moved under the integration testing. These should still work and run the same as before.

Package the base TCK as a docker image. Publish locally with:

```sh
sbt tck/Docker/publishLocal
```

Example of running all from docker, with port binding and using `host.docker.internal`:

```sh
docker run -d --name cloudstate-function -p 8080:8080 cloudstateio/samples-js-shopping-cart
docker run -d --name cloudstate-proxy -p 9000:9000 -e USER_FUNCTION_HOST=host.docker.internal -e USER_FUNCTION_PORT=8090 cloudstateio/cloudstate-proxy-dev-mode

# can check exit status; this will fail if the TCK fails:
docker run --rm --name cloudstate-tck -p 8090:8090 -e TCK_HOST=0.0.0.0 -e TCK_PROXY_HOST=host.docker.internal -e TCK_FRONTEND_HOST=host.docker.internal cloudstateio/cloudstate-tck

docker rm -f cloudstate-proxy
docker rm -f cloudstate-function
```

Or using host network to simplify port binding:

```bash
#!/usr/bin/env bash

set -x

docker run -d --name cloudstate-function --net=host cloudstateio/samples-js-shopping-cart
docker run -d --name cloudstate-proxy --net=host -e USER_FUNCTION_PORT=8090 cloudstateio/cloudstate-proxy-dev-mode

docker run --rm --name cloudstate-tck --net=host cloudstateio/cloudstate-tck
status=$?

docker rm -f cloudstate-proxy
docker rm -f cloudstate-function

exit $status
```

Example run:

```
+ docker run -d --name cloudstate-function --net=host cloudstateio/samples-js-shopping-cart
1100467cdc557a2f58d7c7cc04126e7e87840e63f9427d16b3315e7473b9a4a9
+ docker run -d --name cloudstate-proxy --net=host -e USER_FUNCTION_PORT=8090 cloudstateio/cloudstate-proxy-dev-mode
26dd5270affcc8da22df95b48a09a0e19a1cb0403f3494f3442a480fe0b6062c
+ docker run --rm --name cloudstate-tck --net=host cloudstateio/cloudstate-tck
Run starting. Expected test count is: 5
ConfiguredCloudStateTCK:
Cloudstate TCK
- must verify that the user function process responds
- must verify that an initial GetShoppingCart request succeeds
- must verify that items can be added to, and removed from, a shopping cart
- must verify that the backend supports the ServerReflection API
- must verify that the HTTP API of ShoppingCart protocol works
Run completed in 8 seconds, 730 milliseconds.
Total number of tests run: 5
Suites: completed 1, aborted 0
Tests: succeeded 5, failed 0, canceled 0, ignored 0, pending 0
All tests passed.
+ status=0
+ docker rm -f cloudstate-proxy
cloudstate-proxy
+ docker rm -f cloudstate-function
cloudstate-function
+ exit 0
```

### CODE REVIEW

**Comment by pvlugter** [comment]
@marcellanz @sleipnir could you try out the docker image locally, to see how it will be to use this in language support builds?

**Comment by viktorklang** [comment]
@srikanthops @jroper You'll probably want to have a look at this

**Comment by marcellanz** [comment]
@pvlugter very nice! 
I tested the branch locally and it ran the TCK against the Go language support as expected. 👍

**Comment by sleipnir** [comment]
Hi @pvlugter awesome work!
I ran it locally with Dart and it worked as expected. I test with the host network.
Thanks!

**Comment by sleipnir** [comment]
@pvlugter @viktorklang @marcellanz Now to be perfect I thing we only have to make this image of the tck available on Dockerhub, so we don't need sbt to publish the local image and anyone can run the tck directly from the Dockerhub image

**Comment by viktorklang** [comment]
Publishing a Cloudstate release should include pushing the TCK Docker image
to Dockerhub. And we should probably push a nightly or similar as ”latest”.
Thoughts?
-- 
Cheers,
√

**Comment by marcellanz** [comment]
I welcome a nightly build. If needed I would build locally a new tck image, but having a nightly build would help to just run the tck without beeing in the loop of potential current development where  one needs something like node/npm on the correct version.

Currently the main cloudstate repository runs the TCK against all language support implementations supported and we get a quick feedback about the health of the proxy in combination with all language support libraries. When the support libraries runs the TCK by their own, we loose this information. So, do we like to somehow re-establish that?

**Comment by sleipnir** [comment]
@viktorklang I agree
@marcellanz could we use github tags to support this? Just as some projects use travis tags to indicate the health of the repository, we could use tags to indicate whether support language builds pass and more specifically a tag for tck for each support language.
Would it be very difficult to achieve this kind of thing?

**Comment by marcellanz** [comment]
@sleipnir that would be for master-master combinations, right?
A language support lib would probably not release a new version if it fails against latest proxy released. But a support library could fail temporarily against latest released proxy or even proxies master:

lib-master : proxy-master
lib-master : proxy-vX.Y.Z

and vice-versa. Is this needed? How would we tag this? It seems that needs tag for every nightly build?

(I'm just asking because I don'tunderstand yet how that works yet, not because I think it would not work.)

**Comment by sleipnir** [comment]
@marcellanz  is just an idea, but I have no idea if it is feasible, we would have to include it in the travis pipeline or a customized github workflow

**Comment by marcellanz** [comment]
👍 I like the idea a lot, having the build status reported to the . 
Perhaps I got it wrong, with the tag is it like the build badges travis has?
https://docs.travis-ci.com/user/status-images/

this way I could imagine having a branch or master built and tested against the TCK and if that fails, the badge gets red or the like and this can be used by the main project to track the support libraries health.

**Comment by sleipnir** [comment]
this this this this :D
I said tag wrongly, I wanted to say just like the status of travis

**Comment by pvlugter** [comment]
I've added the TCK docker publish to the travis build. That should be all we need to get release and latest snapshot images published.

**Comment by viktorklang** [comment]
Nice work, @pvlugter!

**Comment by viktorklang** [comment]
@pvlugter @srikanthops @edwardcallahan Can you check what needs to be done in order to make sure that CircleCI works with this?

**Comment by pvlugter** [comment]
The CircleCI native-image integration tests should work same as before (not that they're currently running here). I've pushed this branch to `lightbend/cloudstate-ci` for the CircleCI build, and it passes there:

https://circleci.com/gh/lightbend/cloudstate-ci/74

So this should be good to go. I'll merge and tag, so that there are versioned docker images to start using.

**Comment by pvlugter** [comment]
I've tagged `v0.5.1` and the travis build has published docker images. So the following images can be used for running TCK in language supports:

```
cloudstateio/cloudstate-proxy-dev-mode:0.5.1
cloudstateio/cloudstate-tck:0.5.1
```

Note that the travis build will also publish for any pushes to master under the `latest` tag.

I've also manually published native image build for proxy dev mode:

```
cloudstateio/cloudstate-proxy-native-dev-mode:0.5.1
```

which can also be used when running the TCK.

**Comment by marcellanz** [comment]
@pvlugter nice 👍
I integrate that into the Go support.

**Comment by marcellanz** [comment]
@pvlugter I use these docker images now to verify the Go implementation against the TCK in various combinations like:
- go-tck:latest vs. proxy:latest
- go-tck:latest vs. proxy:0.5.1
- go-tck:latest vs. proxy-native:0.5.1
- go-tck:0.1.0 vs. proxy:latest
- go-tck:0.1.0 vs. proxy-native:latest

I have not yet found a good way to visualize this matrix on a projects README.md or the like.

https://travis-ci.com/github/marcellanz/go-support:
Screenshot 2020-05-21 at 18 02 29

WIP branch for this:
https://github.com/marcellanz/go-support/tree/feature/crdt_support

**Pull request merged**
