### PR TITLE
Update crdt.md

### PR DESCRIPTION
**Pull request by marcoderama**
Some small edits.

### CODE REVIEW

**Comment by viktorklang** [comment]
Thanks @marcoderama! :)

**Comment by viktorklang** [comment]
@srikanthops Do you know if it is possible to have CircleCI surface more diagnostic information on build failures without requirin the user to be authorized via CircleCI?

**Comment by srikanthops** [comment]
@viktorklang I don't know there is an easy way to do that..  let me dig-in
all build failures will show up in slack, but if you want details you have to be on circleCI and can sign up via github.

**Comment by srikanthops** [comment]
On that note, our plan allows 15 users and we are at 8 users for lightbend account

**Pull request merged**
