### PR TITLE
Create JVM Universal Support

### PR DESCRIPTION
**Pull request by sleipnir**
This is a draft PR.

Things that are still needed to get a functional version:

- [x] Rename packages
- [x] Exclude EventSourced and CRDT test implementations
- [x] Create sbt build properties
- [ ] Create sbt docs properties
- [x] Exclude Annotations
- [x] Exclude AnnotationBasedCrdtSupport
- [x] Exclude AnnotationBasedEventSourcedSupport
- [ ] Refactoring public Classes and Interfaces to use native Java types 
- [ ] Refactoring Reflection Helper to respect the inheritance of basic interfaces in another languages
- [ ] Merge java-support 0.5.1 in Master
- [ ] Some docs and examples about how to use

### CODE REVIEW

**Comment by marcellanz** [comment]
Hi @sleipnir, what and in which area do you expect feedback here? Are there any dependencies to other PRs ongoing work being done in parallel?

(Can you please squash "remote-tracking" mentions to get a cleaner history?)

**Comment by sleipnir** [comment]
Thank you @marcellanz  for responding, after the children's day holiday next week I intend to resume this and I will answer you in greater detail. I will try to clean the branch

**Comment by marcellanz** [comment]
> Thank you @marcellanz for responding, after the children's day holiday next week I intend to resume this and I will answer you in greater detail. I will try to clean the branch

Happy holidays! Enjoy the time with the kids Adriano! :)

**Comment by sleipnir** [comment]
I will enjoy the children and enjoy my birthday which is tomorrow :D
Thank you @marcellanz

**Comment by pvlugter** [comment]
Yes, would be great to have this PR clean to make it easier to review. With this currently being a copy, it's not easy to see the simple repackage and move. There may have been some small changes in java-support too. Could we start with just a rename of the package for these files, then a move to a separate project, before we make any other changes?

**Comment by pvlugter** [comment]
I think it would useful to first rename packages within the java-support project — and make sure it's the right separation by having other JVM language supports only use those parts. We can then take it from there.

**Comment by sleipnir** [comment]
Yes I agree, renaming the packages was the first thing I did

**Pull request closed without merging**
