### PR TITLE
Minor updates to README.md to further enhance its flow and readability.

### LINKED ISSUE #86: Make a handful of (minor) updates to README.md to enhance its flow and readability.
- The CloudState `README.md` is just about the coolest guide that I've seen in a great long while; and I've pretty much seen them all. 
- The coherent narrative laid out in the `README.md` has done nothing less for me than give me a manifesto for building (and using) next generation serverless, the way it _should_ be done. Kudos 👍 
- It has, in short order, nicely framed `FaaS` in the context it should be seen; a first (important) step toward stateful cloud computing, but a first step nonetheless 🌩 
- With that, and with utmost respect for the design captured by the author(s) of this terrific `README.md`, I suggest that we make a handful of (minor) updates to it so as to enhance its flow and readability even more than it currently stands.

### PR DESCRIPTION
**Pull request by akramtexas**
Fix #86 

- I know that talk is cheap—dirt cheap when it happens to be mine—so I decided to do something about my points on making (minor) tweaks to the fabulous CloudState `README.md` (Referring here to Issue #86 that I created earlier this Saturday morning).
- I didn't have the permissions to assign Issue #86 to myself (So I reference it here manually).

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @akramtexas,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by akramtexas** [comment]
@viktorklang and @jboner - Gents, as best as I can tell, I've done everything I think needed to be done (as far signing the Lightbend Contributors License Agreement is concerned, for me as an open source contributor) ⬆️

**Comment by akramtexas** [comment]
Ah, good, I got a confirmation email (as follows) regarding open source contributions 😄 
```
mailer@lightbend.com | mailer@lightbend.com | 9:45 AM (7 minutes ago) |   |  
mailer@lightbend.com
Thank you for signing the Lightbend CLA.
If you have already sent a pull request please add a comment to the pull request saying you did sign the CLA.
We are looking forward to your contributions!
The Lightbend Team
email: info@lightbend.com
lightbend.com
```

**Comment by akramtexas** [comment]
> These are some really excellent improvements to the documentation, @akramtexas. Thank you!

- I appreciated that, @viktorklang! Meanwhile, I squashed the commits, and rebased: So this PR should be good to go and merge into `master` after the build checks underway have passed 🏁 
- BTW, a handful of times a year, working with Git tends to land me in a scenario or two where extricating myself (from the usually self-induced git morass) will be _orders_ of magnitude trickier than the given code change-set itself that I've worked on 😉 
- Such was the case earlier this morning: To spare you the gory details of the scenario, suffice it to say that I had moved all `CloudState` DEV work to a different Mac station than the one I use for my daytime work 🌞  and resumed the work (of reconciling PR comments) on the `CloudState` DEV Mac station 💻 
- Looking at the build checks actually, I trust that we're good to go. I can't merge, however, until I get WRITE access...

**Comment by akramtexas** [comment]
Given the notification above (i.e. `Only those with write access to this repository can merge pull requests.`) and referring to Issue #86, if someone can please merge this PR on my behalf, that is another option whereby we can avoid repeated `git rebase`s 👍

**Comment by viktorklang** [comment]
Hi @akramtexas, are all the files in this PR really modified? Perhaps you'll want to do a soft-reset on your branch and then add the appropriate changes interactively and push again? Let me know if you need any help!

**Comment by akramtexas** [comment]
> Hi @akramtexas, are all the files in this PR really modified? Perhaps you'll want to do a soft-reset on your branch and then add the appropriate changes interactively and push again? Let me know if you need any help!

Hi @viktorklang, great question: Actually, my theory all along has been to modify `README.md` alone, and nothing else. Alas, and to spare you the gory details of the lovely Git scenario I found myself in, suffice it to say that I had moved all CloudState DEV work to a different Mac station (my `CloudState DEV Mac station` 💻) than the one I use for my daytime work during the process of straddling this PR, resuming the work (of reconciling PR comments) on my `CloudState DEV Mac station` 💻 - Hence the twilight zone we are witnessing. Not to worry, and thank you for the thoughtful suggestion on tackling Git into submission here, so to say 👍 I will make it so. Again, thanks for the kind offer 😅

**Comment by viktorklang** [comment]
@akramtexas Ah! The PR now looks like it changes 158 files. Might be easiest to checkout a new branch from masters and porting over the README.md changes to that directly, and opening another PR?

**Comment by akramtexas** [comment]
> @akramtexas Ah! The PR now looks like it changes 158 files. Might be easiest to checkout a new branch from masters and porting over the README.md changes to that directly, and opening another PR?

@viktorklang Ah goodness, yes: There is much wisdom to what you say. Gotcha, and I'm on it, starting with (closing this PR and) opening a new PR ✅ - Rest assured, compared to my `Git` manners, my programming and design ventures are (far) more solid, _and_ stolid 😉

**Pull request closed without merging**
